package login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import login.loginFram;
import java.text.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import org.bson.Document;





/**
 *
 * @author arthe
 */
public class fillPage extends javax.swing.JFrame {
    
    public String th;
    public String mc;
    public String mcn;
    private Object JFRAME_JTABLE;
    public fillPage() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);//setFullscreen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtRecord = new javax.swing.JLabel();
        jtMachineNumber = new javax.swing.JLabel();
        jtDevicename = new javax.swing.JLabel();
        jtLocation = new javax.swing.JLabel();
        jc_Device = new javax.swing.JComboBox<>();
        jc_Machinenumber = new javax.swing.JComboBox<>();
        jc_Location = new javax.swing.JComboBox<>();
        jTF_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JTF_reportFill = new javax.swing.JTextField();
        jb_Submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        passCheck = new javax.swing.JCheckBox();
        troublesCheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        TF_Date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtRecord.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtRecord.setText("Record of equipment inspection");

        jtMachineNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtMachineNumber.setText("Machine number");

        jtDevicename.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtDevicename.setText("Device name");

        jtLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtLocation.setText("Location");

        jc_Device.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Projector", "Air", "Smart Ticket", "" }));
        jc_Device.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_DeviceActionPerformed(evt);
            }
        });

        jc_Machinenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_MachinenumberActionPerformed(evt);
            }
        });

        jc_Location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theater1", "Theater2", "Theater3", "Theater4", "Theater5", " " }));
        jc_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_LocationActionPerformed(evt);
            }
        });

        jTF_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Investigator's name");

        JTF_reportFill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JTF_reportFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_reportFillActionPerformed(evt);
            }
        });

        jb_Submit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jb_Submit.setText("SUBMIT");
        jb_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("report a problem");

        passCheck.setText("Pass");
        passCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCheckActionPerformed(evt);
            }
        });

        troublesCheck.setText("Trouble");
        troublesCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troublesCheckActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtLocation)
                            .addComponent(jLabel2)
                            .addComponent(JTF_reportFill, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jtMachineNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                    .addComponent(jc_Machinenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jtDevicename)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jc_Device, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jc_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(124, 124, 124)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTF_name, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                            .addComponent(TF_Date)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passCheck)
                                .addGap(18, 18, 18)
                                .addComponent(troublesCheck))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jb_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLocation)
                    .addComponent(jc_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDevicename)
                    .addComponent(jc_Device, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMachineNumber)
                    .addComponent(jc_Machinenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passCheck)
                    .addComponent(troublesCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(JTF_reportFill, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jc_MachinenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_MachinenumberActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_jc_MachinenumberActionPerformed

    private void jc_DeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_DeviceActionPerformed
        // TODO add your handling code here
        if(jc_Device.getSelectedItem().equals("Projector")){
            jc_Machinenumber.removeAllItems();
            jc_Machinenumber.setSelectedItem(null);
            jc_Machinenumber.addItem("aaaa");
            jc_Machinenumber.addItem("bbbb");
        }else if(jc_Device.getSelectedItem().equals("Air")){
            jc_Machinenumber.removeAllItems();
            jc_Machinenumber.setSelectedItem(null);
            jc_Machinenumber.addItem("cccc");
            jc_Machinenumber.addItem("dddd");
        }else if(jc_Device.getSelectedItem().equals("Smart Ticket")){
            jc_Machinenumber.removeAllItems();
            jc_Machinenumber.setSelectedItem(null);
            jc_Machinenumber.addItem("eee");
            jc_Machinenumber.addItem("fff");
        }
//        String selectTheator = jc_Location.getSelectedItem().toString();
//        String selectItem = jc_Device.getSelectedItem().toString();
//        String selectMacineNumber = jc_Machinenumber.getSelectedItem().toString();
//        jtSelect.setText(selectTheator+"\t"+selectItem+"\t"+selectMacineNumber);
    }//GEN-LAST:event_jc_DeviceActionPerformed

    private void jc_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_LocationActionPerformed
        if(jc_Location.getSelectedItem().equals("Theator1")){
            jc_Device.removeAllItems();
            jc_Device.setSelectedItem(null);
            jc_Device.addItem("Projector");
            jc_Device.addItem("Air");
            jc_Device.addItem("Smart Ticket");
        }
        else if(jc_Location.getSelectedItem().equals("Theator2")){
            jc_Device.removeAllItems();
            jc_Device.setSelectedItem(null);
            jc_Device.addItem("Projector");
            jc_Device.addItem("Air");
            jc_Device.addItem("Smart Ticket");
        }
        else if(jc_Location.getSelectedItem().equals("Theator3")){
            jc_Device.removeAllItems();
            jc_Device.setSelectedItem(null);
            jc_Device.addItem("Projector");
            jc_Device.addItem("Air");
            jc_Device.addItem("Smart Ticket");
        }
        else if(jc_Location.getSelectedItem().equals("Theator4")){
            jc_Device.removeAllItems();
            jc_Device.setSelectedItem(null);
            jc_Device.addItem("Projector");
            jc_Device.addItem("Air");
            jc_Device.addItem("Smart Ticket");
        }
        else if(jc_Location.getSelectedItem().equals("Theator5")){
            jc_Device.removeAllItems();
            jc_Device.setSelectedItem(null);
            jc_Device.addItem("Projector");
            jc_Device.addItem("Air");
            jc_Device.addItem("Smart Ticket");
        }
    }//GEN-LAST:event_jc_LocationActionPerformed

    private void jb_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SubmitActionPerformed
        
        MongoClient client = MongoClients.create("mongodb+srv://momo:momo@cluster0.6kamogv.mongodb.net/");  //เชื่อมต่อเข้ากับ mongodb
        MongoDatabase db = client.getDatabase("OOPproject");
        MongoCollection<Document> col = db.getCollection("Collection");
        MongoCollection<Document> col2 = db.getCollection("Chart");
        
        Document field = new Document();
        field.append("name",jTF_name.getText());
        field.append("date",TF_Date.getText());
        field.append("location",jc_Location.getSelectedItem().toString());
        field.append("device",jc_Device.getSelectedItem().toString());
        field.append("machinenumber",jc_Machinenumber.getSelectedItem().toString());
        field.append("report",JTF_reportFill.getText());
        if(passCheck.isSelected()){
            //System.out.println("Pass!");
            field.append("status","Pass");
            Document filter = new Document("_id", "1");

            // สร้างเงื่อนไขในการเพิ่มค่าในฟิลด์
            Document update = new Document("$inc", new Document("number", 1));
            col2.updateOne(filter, update);
        }
        else{
            field.append("status","Trouble");
            Document filter = new Document("_id", "2");

            // สร้างเงื่อนไขในการเพิ่มค่าในฟิลด์
            Document update = new Document("$inc", new Document("number", 1));
            col2.updateOne(filter, update);
        }
        col.insertOne(field);
        
        
        dataPage DP = new dataPage();
        DP.show();//show datapage
        dispose();//close fillpage when datapage show
        for (Document document : col.find()) {   //ท่องไปใน Collection เเล้ว get string 
            String value1 = document.getString("name");
            String value2 = document.getString("date");
            String value3 = document.getString("location");
            String value4 = document.getString("device");
            String value5 = document.getString("machinenumber");
            String value6 = document.getString("report");
            String value7 = document.getString("status");
            dataPage.AddRowToTable(new String[]{value1, value2, value3 ,value4 ,value5, "STATUS : " + value7 + " หมายเหตุ : " +value6});
        }
        client.close();
        
    }//GEN-LAST:event_jb_SubmitActionPerformed

    private void JTF_reportFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_reportFillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_reportFillActionPerformed

    private void passCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCheckActionPerformed
         if(passCheck.isSelected()){
            troublesCheck.setSelected(false);
        }
    }//GEN-LAST:event_passCheckActionPerformed

    private void troublesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troublesCheckActionPerformed
        // TODO add your handling code here:
        if(troublesCheck.isSelected()){
            passCheck.setSelected(false);
        }
    }//GEN-LAST:event_troublesCheckActionPerformed

    private void jTF_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fillPage().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTF_reportFill;
    private javax.swing.JTextField TF_Date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTF_name;
    private javax.swing.JButton jb_Submit;
    private javax.swing.JComboBox<String> jc_Device;
    private javax.swing.JComboBox<String> jc_Location;
    private javax.swing.JComboBox<String> jc_Machinenumber;
    private javax.swing.JLabel jtDevicename;
    private javax.swing.JLabel jtLocation;
    private javax.swing.JLabel jtMachineNumber;
    private javax.swing.JLabel jtRecord;
    private javax.swing.JCheckBox passCheck;
    private javax.swing.JCheckBox troublesCheck;
    // End of variables declaration//GEN-END:variables


}