/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restuarantReservation;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sitap
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        booking = new javax.swing.JLabel();
        resBox = new javax.swing.JComboBox<>();
        res = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        personBox = new javax.swing.JComboBox<>();
        person = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        note = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteText = new javax.swing.JTextArea();
        booked = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(413, 735));
        setSize(new java.awt.Dimension(413, 735));

        booking.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        booking.setText("Booking");

        resBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Res 1", "Res 2", "Res 3", "Res 4", "Res 5", "Res 6" }));
        resBox.setPreferredSize(new java.awt.Dimension(72, 30));
        resBox.setFont(new java.awt.Font("Dialog", 0, 13));
        resBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBoxActionPerformed(evt);
            }
        });

        res.setText("Restuarant");
        res.setFont(new java.awt.Font("Dialog", 1, 13));

        date.setText("Date");
        date.setFont(new java.awt.Font("Dialog", 1, 13));
        
        time.setText("Time");
        time.setFont(new java.awt.Font("Dialog", 1, 13));
        
        personBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 person", "2 person", "3 person", "4 person", "5 person", "6 person", "10 person" }));
        personBox.setPreferredSize(new java.awt.Dimension(72, 30));
        personBox.setFont(new java.awt.Font("Dialog", 0, 13));
        personBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personBoxActionPerformed(evt);
            }
        });

        person.setText("Person");
        person.setFont(new java.awt.Font("Dialog", 1, 13));
        
        name.setText("Name");
        name.setFont(new java.awt.Font("Dialog", 1, 13));
        
        nameText.setFont(new java.awt.Font("Dialog", 0, 13));
        
        note.setText("Addition Note");
        note.setFont(new java.awt.Font("Dialog", 1, 13));
        
        noteText.setColumns(20);
        noteText.setRows(5);
        noteText.setFont(new java.awt.Font("Dialog", 0, 13));
        jScrollPane1.setViewportView(noteText);

        booked.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        booked.setText("Booking");
        booked.setPreferredSize(new java.awt.Dimension(222, 40));
        booked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookedActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personBox, 0, 295, Short.MAX_VALUE)
                            .addComponent(person)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(booking)
                            .addComponent(res)
                            .addComponent(nameText)
                            .addComponent(note)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(booked, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(booking)
                .addGap(18, 18, 18)
                .addComponent(res)
                .addGap(4, 4, 4)
                .addComponent(resBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(time))
                .addGap(43, 43, 43)
                .addComponent(person)
                .addGap(4, 4, 4)
                .addComponent(personBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(note)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(booked, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    protected void bookedActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	JOptionPane.showMessageDialog(null, "Booking Success");
	}

	private void resBoxActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void personBoxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, "Failed to apply look-and-feel.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton booked;
    private javax.swing.JLabel booking;
    private javax.swing.JLabel date;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel note;
    private javax.swing.JTextArea noteText;
    private javax.swing.JLabel person;
    private javax.swing.JComboBox<String> personBox;
    private javax.swing.JLabel res;
    private javax.swing.JComboBox<String> resBox;
    private javax.swing.JLabel time;
    // End of variables declaration                   
}
