/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restuarantReservation;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sitap
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        img_1 = new javax.swing.JLabel();
        img_2 = new javax.swing.JLabel();
        img_3 = new javax.swing.JLabel();
        img_4 = new javax.swing.JLabel();
        img_5 = new javax.swing.JLabel();
        img_6 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        res_1 = new javax.swing.JLabel();
        res_2 = new javax.swing.JLabel();
        res_4 = new javax.swing.JLabel();
        res_3 = new javax.swing.JLabel();
        res_5 = new javax.swing.JLabel();
        res_6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(413, 735));

        img_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restuarantReservation/res_1.jpg"))); // NOI18N

        img_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restuarantReservation/res_2.jpg"))); // NOI18N

        img_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restuarantReservation/res_3.png"))); // NOI18N

        img_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restuarantReservation/res_4.jpg"))); // NOI18N

        img_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restuarantReservation/res_5.jpg"))); // NOI18N

        img_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restuarantReservation/res_6.jpg"))); // NOI18N

        welcome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        welcome.setText("Welcome, USER");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        res_1.setText("res_1");

        res_2.setText("res_2");

        res_4.setText("res_4");

        res_3.setText("res_3");

        res_5.setText("res_5");

        res_6.setText("res_6");

        img_1.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_1 r1 = new Res_1();
                r1.setVisible(true);
                dispose();
        	}
        });
        res_1.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_1 r1 = new Res_1();
                r1.setVisible(true);
                dispose();
        	}
        });
        
        img_2.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_2 r2 = new Res_2();
                r2.setVisible(true);
                dispose();
        	}
        });
        res_2.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_2 r2 = new Res_2();
                r2.setVisible(true);
                dispose();
        	}
        });
        
        img_3.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_3 r3 = new Res_3();
                r3.setVisible(true);
                dispose();
        	}
        });
        res_3.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_3 r3 = new Res_3();
                r3.setVisible(true);
                dispose();
        	}
        });
        
        img_4.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_4 r4 = new Res_4();
                r4.setVisible(true);
                dispose();
        	}
        });
        res_4.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_4 r4 = new Res_4();
                r4.setVisible(true);
                dispose();
        	}
        });

        img_5.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_5 r5 = new Res_5();
                r5.setVisible(true);
                dispose();
        	}
        });
        res_5.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_5 r5 = new Res_5();
                r5.setVisible(true);
                dispose();
        	}
        });
        
        img_6.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_6 r6 = new Res_6();
                r6.setVisible(true);
                dispose();
        	}
        });
        res_6.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e) {
        		Res_6 r6 = new Res_6();
                r6.setVisible(true);
                dispose();
        	}
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(img_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(img_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(img_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(res_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(res_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(res_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(res_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(img_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(img_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(img_6))
                            .addComponent(res_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(res_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(welcome)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(res_1)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_3)
                            .addComponent(img_4)))
                    .addComponent(res_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(res_4)
                    .addComponent(res_3))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_6)
                    .addComponent(img_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(res_5)
                    .addComponent(res_6))
                .addGap(88, 88, 88)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, "Failed to apply look-and-feel.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel img_1;
    private javax.swing.JLabel img_2;
    private javax.swing.JLabel img_3;
    private javax.swing.JLabel img_4;
    private javax.swing.JLabel img_5;
    private javax.swing.JLabel img_6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel res_1;
    private javax.swing.JLabel res_2;
    private javax.swing.JLabel res_3;
    private javax.swing.JLabel res_4;
    private javax.swing.JLabel res_5;
    private javax.swing.JLabel res_6;
    private javax.swing.JLabel welcome;
    // End of variables declaration                   
}
